name: 🚀 Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        uses: wei/curl@v1
        with:
          args: >
            -X POST
            -H "Accept: application/json"
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploy
